//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 2.0.50727.3053.
// 
#pragma warning disable 1591

namespace PWSTestClient.TrackingProxy {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="TrackingServiceEndpoint", Namespace="http://purolator.com/pws/service/v1")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ResponseContainer))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(RequestContainer))]
    public partial class TrackingService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private RequestContext requestContextValueField;
        
        private ResponseContext responseContextValueField;
        
        private System.Threading.SendOrPostCallback TrackPackagesByPinOperationCompleted;
        
        private System.Threading.SendOrPostCallback TrackPackagesByReferenceOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetDeliveryDetailsOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public TrackingService() {
            this.Url = global::PWSTestClient.Properties.Settings.Default.PWSTestClient_TrackingProxy_TrackingService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public RequestContext RequestContextValue {
            get {
                return this.requestContextValueField;
            }
            set {
                this.requestContextValueField = value;
            }
        }
        
        public ResponseContext ResponseContextValue {
            get {
                return this.responseContextValueField;
            }
            set {
                this.responseContextValueField = value;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event TrackPackagesByPinCompletedEventHandler TrackPackagesByPinCompleted;
        
        /// <remarks/>
        public event TrackPackagesByReferenceCompletedEventHandler TrackPackagesByReferenceCompleted;
        
        /// <remarks/>
        public event GetDeliveryDetailsCompletedEventHandler GetDeliveryDetailsCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("ResponseContextValue", Direction=System.Web.Services.Protocols.SoapHeaderDirection.Out)]
        [System.Web.Services.Protocols.SoapHeaderAttribute("RequestContextValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://purolator.com/pws/service/v1/TrackPackagesByPin", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("TrackPackagesByPinResponse", Namespace="http://purolator.com/pws/datatypes/v1", IsNullable=true)]
        public TrackPackagesByPinResponseContainer TrackPackagesByPin([System.Xml.Serialization.XmlElementAttribute(Namespace="http://purolator.com/pws/datatypes/v1", IsNullable=true)] TrackPackagesByPinRequestContainer TrackPackagesByPinRequest) {
            object[] results = this.Invoke("TrackPackagesByPin", new object[] {
                        TrackPackagesByPinRequest});
            return ((TrackPackagesByPinResponseContainer)(results[0]));
        }
        
        /// <remarks/>
        public void TrackPackagesByPinAsync(TrackPackagesByPinRequestContainer TrackPackagesByPinRequest) {
            this.TrackPackagesByPinAsync(TrackPackagesByPinRequest, null);
        }
        
        /// <remarks/>
        public void TrackPackagesByPinAsync(TrackPackagesByPinRequestContainer TrackPackagesByPinRequest, object userState) {
            if ((this.TrackPackagesByPinOperationCompleted == null)) {
                this.TrackPackagesByPinOperationCompleted = new System.Threading.SendOrPostCallback(this.OnTrackPackagesByPinOperationCompleted);
            }
            this.InvokeAsync("TrackPackagesByPin", new object[] {
                        TrackPackagesByPinRequest}, this.TrackPackagesByPinOperationCompleted, userState);
        }
        
        private void OnTrackPackagesByPinOperationCompleted(object arg) {
            if ((this.TrackPackagesByPinCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.TrackPackagesByPinCompleted(this, new TrackPackagesByPinCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("ResponseContextValue", Direction=System.Web.Services.Protocols.SoapHeaderDirection.Out)]
        [System.Web.Services.Protocols.SoapHeaderAttribute("RequestContextValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://purolator.com/pws/service/v1/TrackPackagesByReference", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("TrackPackagesByReferenceResponse", Namespace="http://purolator.com/pws/datatypes/v1", IsNullable=true)]
        public TrackPackagesByReferenceResponseContainer TrackPackagesByReference([System.Xml.Serialization.XmlElementAttribute(Namespace="http://purolator.com/pws/datatypes/v1", IsNullable=true)] TrackPackagesByReferenceRequestContainer TrackPackagesByReferenceRequest) {
            object[] results = this.Invoke("TrackPackagesByReference", new object[] {
                        TrackPackagesByReferenceRequest});
            return ((TrackPackagesByReferenceResponseContainer)(results[0]));
        }
        
        /// <remarks/>
        public void TrackPackagesByReferenceAsync(TrackPackagesByReferenceRequestContainer TrackPackagesByReferenceRequest) {
            this.TrackPackagesByReferenceAsync(TrackPackagesByReferenceRequest, null);
        }
        
        /// <remarks/>
        public void TrackPackagesByReferenceAsync(TrackPackagesByReferenceRequestContainer TrackPackagesByReferenceRequest, object userState) {
            if ((this.TrackPackagesByReferenceOperationCompleted == null)) {
                this.TrackPackagesByReferenceOperationCompleted = new System.Threading.SendOrPostCallback(this.OnTrackPackagesByReferenceOperationCompleted);
            }
            this.InvokeAsync("TrackPackagesByReference", new object[] {
                        TrackPackagesByReferenceRequest}, this.TrackPackagesByReferenceOperationCompleted, userState);
        }
        
        private void OnTrackPackagesByReferenceOperationCompleted(object arg) {
            if ((this.TrackPackagesByReferenceCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.TrackPackagesByReferenceCompleted(this, new TrackPackagesByReferenceCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("ResponseContextValue", Direction=System.Web.Services.Protocols.SoapHeaderDirection.Out)]
        [System.Web.Services.Protocols.SoapHeaderAttribute("RequestContextValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://purolator.com/pws/service/v1/GetDeliveryDetails", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("GetDeliveryDetailsResponse", Namespace="http://purolator.com/pws/datatypes/v1", IsNullable=true)]
        public GetDeliveryDetailsResponseContainer GetDeliveryDetails([System.Xml.Serialization.XmlElementAttribute(Namespace="http://purolator.com/pws/datatypes/v1", IsNullable=true)] GetDeliveryDetailsRequestContainer GetDeliveryDetailsRequest) {
            object[] results = this.Invoke("GetDeliveryDetails", new object[] {
                        GetDeliveryDetailsRequest});
            return ((GetDeliveryDetailsResponseContainer)(results[0]));
        }
        
        /// <remarks/>
        public void GetDeliveryDetailsAsync(GetDeliveryDetailsRequestContainer GetDeliveryDetailsRequest) {
            this.GetDeliveryDetailsAsync(GetDeliveryDetailsRequest, null);
        }
        
        /// <remarks/>
        public void GetDeliveryDetailsAsync(GetDeliveryDetailsRequestContainer GetDeliveryDetailsRequest, object userState) {
            if ((this.GetDeliveryDetailsOperationCompleted == null)) {
                this.GetDeliveryDetailsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetDeliveryDetailsOperationCompleted);
            }
            this.InvokeAsync("GetDeliveryDetails", new object[] {
                        GetDeliveryDetailsRequest}, this.GetDeliveryDetailsOperationCompleted, userState);
        }
        
        private void OnGetDeliveryDetailsOperationCompleted(object arg) {
            if ((this.GetDeliveryDetailsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetDeliveryDetailsCompleted(this, new GetDeliveryDetailsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3053")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://purolator.com/pws/datatypes/v1")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://purolator.com/pws/datatypes/v1", IsNullable=true)]
    public partial class ResponseContext : System.Web.Services.Protocols.SoapHeader {
        
        private string responseReferenceField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ResponseReference {
            get {
                return this.responseReferenceField;
            }
            set {
                this.responseReferenceField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3053")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://purolator.com/pws/datatypes/v1")]
    public partial class OnDeliveryScanDetails {
        
        private string deliveryAddressField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string DeliveryAddress {
            get {
                return this.deliveryAddressField;
            }
            set {
                this.deliveryAddressField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3053")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://purolator.com/pws/datatypes/v1")]
    public partial class PhoneNumber {
        
        private string countryCodeField;
        
        private string areaCodeField;
        
        private string phoneField;
        
        private string extensionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string CountryCode {
            get {
                return this.countryCodeField;
            }
            set {
                this.countryCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string AreaCode {
            get {
                return this.areaCodeField;
            }
            set {
                this.areaCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Phone {
            get {
                return this.phoneField;
            }
            set {
                this.phoneField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Extension {
            get {
                return this.extensionField;
            }
            set {
                this.extensionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3053")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://purolator.com/pws/datatypes/v1")]
    public partial class Address {
        
        private string nameField;
        
        private string companyField;
        
        private string departmentField;
        
        private string streetNumberField;
        
        private string streetSuffixField;
        
        private string streetNameField;
        
        private string streetTypeField;
        
        private string streetDirectionField;
        
        private string suiteField;
        
        private string floorField;
        
        private string streetAddress2Field;
        
        private string streetAddress3Field;
        
        private string cityField;
        
        private string provinceField;
        
        private string countryField;
        
        private string postalCodeField;
        
        private PhoneNumber phoneNumberField;
        
        private PhoneNumber faxNumberField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Company {
            get {
                return this.companyField;
            }
            set {
                this.companyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Department {
            get {
                return this.departmentField;
            }
            set {
                this.departmentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string StreetNumber {
            get {
                return this.streetNumberField;
            }
            set {
                this.streetNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string StreetSuffix {
            get {
                return this.streetSuffixField;
            }
            set {
                this.streetSuffixField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string StreetName {
            get {
                return this.streetNameField;
            }
            set {
                this.streetNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string StreetType {
            get {
                return this.streetTypeField;
            }
            set {
                this.streetTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string StreetDirection {
            get {
                return this.streetDirectionField;
            }
            set {
                this.streetDirectionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Suite {
            get {
                return this.suiteField;
            }
            set {
                this.suiteField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Floor {
            get {
                return this.floorField;
            }
            set {
                this.floorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string StreetAddress2 {
            get {
                return this.streetAddress2Field;
            }
            set {
                this.streetAddress2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string StreetAddress3 {
            get {
                return this.streetAddress3Field;
            }
            set {
                this.streetAddress3Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string City {
            get {
                return this.cityField;
            }
            set {
                this.cityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Province {
            get {
                return this.provinceField;
            }
            set {
                this.provinceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Country {
            get {
                return this.countryField;
            }
            set {
                this.countryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string PostalCode {
            get {
                return this.postalCodeField;
            }
            set {
                this.postalCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public PhoneNumber PhoneNumber {
            get {
                return this.phoneNumberField;
            }
            set {
                this.phoneNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public PhoneNumber FaxNumber {
            get {
                return this.faxNumberField;
            }
            set {
                this.faxNumberField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3053")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://purolator.com/pws/datatypes/v1")]
    public partial class ProofOfPickUpScanDetails {
        
        private string pickUpConfirmationNumberField;
        
        private Address pickUpAddressField;
        
        private string pickUpContactNameField;
        
        private string pickUpCompanyNameField;
        
        private string pickUpLocationField;
        
        private string commitedDeliveryDateField;
        
        private string premiumServiceTextField;
        
        private string productTypeTextField;
        
        private string specialHandlingTextField;
        
        private string paymentTypeTextField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string PickUpConfirmationNumber {
            get {
                return this.pickUpConfirmationNumberField;
            }
            set {
                this.pickUpConfirmationNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public Address PickUpAddress {
            get {
                return this.pickUpAddressField;
            }
            set {
                this.pickUpAddressField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string PickUpContactName {
            get {
                return this.pickUpContactNameField;
            }
            set {
                this.pickUpContactNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string PickUpCompanyName {
            get {
                return this.pickUpCompanyNameField;
            }
            set {
                this.pickUpCompanyNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string PickUpLocation {
            get {
                return this.pickUpLocationField;
            }
            set {
                this.pickUpLocationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string CommitedDeliveryDate {
            get {
                return this.commitedDeliveryDateField;
            }
            set {
                this.commitedDeliveryDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string PremiumServiceText {
            get {
                return this.premiumServiceTextField;
            }
            set {
                this.premiumServiceTextField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ProductTypeText {
            get {
                return this.productTypeTextField;
            }
            set {
                this.productTypeTextField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string SpecialHandlingText {
            get {
                return this.specialHandlingTextField;
            }
            set {
                this.specialHandlingTextField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string PaymentTypeText {
            get {
                return this.paymentTypeTextField;
            }
            set {
                this.paymentTypeTextField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3053")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://purolator.com/pws/datatypes/v1")]
    public partial class InternationalOutboundScanDetails {
        
        private string destinationPostalCodeField;
        
        private string airportCodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string DestinationPostalCode {
            get {
                return this.destinationPostalCodeField;
            }
            set {
                this.destinationPostalCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string AirportCode {
            get {
                return this.airportCodeField;
            }
            set {
                this.airportCodeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3053")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://purolator.com/pws/datatypes/v1")]
    public partial class DeliveryScanDetails {
        
        private string deliverySignatureField;
        
        private string signatureImageField;
        
        private int signatureImageSizeField;
        
        private SignatureImageFormat signatureImageFormatField;
        
        private string deliveryAddressField;
        
        private string deliveryCompanyNameField;
        
        private string premiumServiceTextField;
        
        private string productTypeTextField;
        
        private string specialHandlingTextField;
        
        private string paymentTypeTextField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string DeliverySignature {
            get {
                return this.deliverySignatureField;
            }
            set {
                this.deliverySignatureField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string SignatureImage {
            get {
                return this.signatureImageField;
            }
            set {
                this.signatureImageField = value;
            }
        }
        
        /// <remarks/>
        public int SignatureImageSize {
            get {
                return this.signatureImageSizeField;
            }
            set {
                this.signatureImageSizeField = value;
            }
        }
        
        /// <remarks/>
        public SignatureImageFormat SignatureImageFormat {
            get {
                return this.signatureImageFormatField;
            }
            set {
                this.signatureImageFormatField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string DeliveryAddress {
            get {
                return this.deliveryAddressField;
            }
            set {
                this.deliveryAddressField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string DeliveryCompanyName {
            get {
                return this.deliveryCompanyNameField;
            }
            set {
                this.deliveryCompanyNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string PremiumServiceText {
            get {
                return this.premiumServiceTextField;
            }
            set {
                this.premiumServiceTextField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ProductTypeText {
            get {
                return this.productTypeTextField;
            }
            set {
                this.productTypeTextField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string SpecialHandlingText {
            get {
                return this.specialHandlingTextField;
            }
            set {
                this.specialHandlingTextField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string PaymentTypeText {
            get {
                return this.paymentTypeTextField;
            }
            set {
                this.paymentTypeTextField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3053")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://purolator.com/pws/datatypes/v1")]
    public enum SignatureImageFormat {
        
        /// <remarks/>
        GIF,
        
        /// <remarks/>
        Bitmap,
        
        /// <remarks/>
        OriginalUncompressed,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3053")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://purolator.com/pws/datatypes/v1")]
    public partial class UndeliverableScanDetails {
        
        private string attemptedDeliveryAddressField;
        
        private string deliveryCompanyNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string AttemptedDeliveryAddress {
            get {
                return this.attemptedDeliveryAddressField;
            }
            set {
                this.attemptedDeliveryAddressField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string DeliveryCompanyName {
            get {
                return this.deliveryCompanyNameField;
            }
            set {
                this.deliveryCompanyNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3053")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://purolator.com/pws/datatypes/v1")]
    public partial class Depot {
        
        private string nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(OnDeliveryScan))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ProofOfPickUpScan))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(InternationalOutboundScan))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DeliveryScan))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(UndeliverableScan))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3053")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://purolator.com/pws/datatypes/v1")]
    public partial class Scan {
        
        private string scanTypeField;
        
        private PIN pINField;
        
        private Depot depotField;
        
        private string scanDateField;
        
        private string scanTimeField;
        
        private string descriptionField;
        
        private string commentField;
        
        private bool summaryScanIndicatorField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ScanType {
            get {
                return this.scanTypeField;
            }
            set {
                this.scanTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public PIN PIN {
            get {
                return this.pINField;
            }
            set {
                this.pINField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public Depot Depot {
            get {
                return this.depotField;
            }
            set {
                this.depotField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ScanDate {
            get {
                return this.scanDateField;
            }
            set {
                this.scanDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ScanTime {
            get {
                return this.scanTimeField;
            }
            set {
                this.scanTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Comment {
            get {
                return this.commentField;
            }
            set {
                this.commentField = value;
            }
        }
        
        /// <remarks/>
        public bool SummaryScanIndicator {
            get {
                return this.summaryScanIndicatorField;
            }
            set {
                this.summaryScanIndicatorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3053")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://purolator.com/pws/datatypes/v1")]
    public partial class PIN {
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3053")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://purolator.com/pws/datatypes/v1")]
    public partial class OnDeliveryScan : Scan {
        
        private OnDeliveryScanDetails scanDetailsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public OnDeliveryScanDetails ScanDetails {
            get {
                return this.scanDetailsField;
            }
            set {
                this.scanDetailsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3053")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://purolator.com/pws/datatypes/v1")]
    public partial class ProofOfPickUpScan : Scan {
        
        private ProofOfPickUpScanDetails scanDetailsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public ProofOfPickUpScanDetails ScanDetails {
            get {
                return this.scanDetailsField;
            }
            set {
                this.scanDetailsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3053")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://purolator.com/pws/datatypes/v1")]
    public partial class InternationalOutboundScan : Scan {
        
        private InternationalOutboundScanDetails scanDetailsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public InternationalOutboundScanDetails ScanDetails {
            get {
                return this.scanDetailsField;
            }
            set {
                this.scanDetailsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3053")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://purolator.com/pws/datatypes/v1")]
    public partial class DeliveryScan : Scan {
        
        private DeliveryScanDetails scanDetailsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public DeliveryScanDetails ScanDetails {
            get {
                return this.scanDetailsField;
            }
            set {
                this.scanDetailsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3053")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://purolator.com/pws/datatypes/v1")]
    public partial class UndeliverableScan : Scan {
        
        private UndeliverableScanDetails scanDetailsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public UndeliverableScanDetails ScanDetails {
            get {
                return this.scanDetailsField;
            }
            set {
                this.scanDetailsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3053")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://purolator.com/pws/datatypes/v1")]
    public partial class TrackingInformation {
        
        private PIN pINField;
        
        private Scan[] scansField;
        
        private ResponseInformation responseInformationField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public PIN PIN {
            get {
                return this.pINField;
            }
            set {
                this.pINField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        public Scan[] Scans {
            get {
                return this.scansField;
            }
            set {
                this.scansField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public ResponseInformation ResponseInformation {
            get {
                return this.responseInformationField;
            }
            set {
                this.responseInformationField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3053")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://purolator.com/pws/datatypes/v1")]
    public partial class ResponseInformation {
        
        private Error[] errorsField;
        
        private InformationalMessage[] informationalMessagesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        public Error[] Errors {
            get {
                return this.errorsField;
            }
            set {
                this.errorsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        public InformationalMessage[] InformationalMessages {
            get {
                return this.informationalMessagesField;
            }
            set {
                this.informationalMessagesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3053")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://purolator.com/pws/datatypes/v1")]
    public partial class Error {
        
        private string codeField;
        
        private string descriptionField;
        
        private string additionalInformationField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string AdditionalInformation {
            get {
                return this.additionalInformationField;
            }
            set {
                this.additionalInformationField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3053")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://purolator.com/pws/datatypes/v1")]
    public partial class InformationalMessage {
        
        private string codeField;
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(GetDeliveryDetailsResponseContainer))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(TrackPackagesByReferenceResponseContainer))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(TrackPackagesByPinResponseContainer))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3053")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://purolator.com/pws/datatypes/v1")]
    public partial class ResponseContainer {
        
        private ResponseInformation responseInformationField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public ResponseInformation ResponseInformation {
            get {
                return this.responseInformationField;
            }
            set {
                this.responseInformationField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3053")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://purolator.com/pws/datatypes/v1")]
    public partial class GetDeliveryDetailsResponseContainer : ResponseContainer {
        
        private DeliveryScan deliveryDetailsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public DeliveryScan DeliveryDetails {
            get {
                return this.deliveryDetailsField;
            }
            set {
                this.deliveryDetailsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3053")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://purolator.com/pws/datatypes/v1")]
    public partial class TrackPackagesByReferenceResponseContainer : ResponseContainer {
        
        private TrackingInformation[] trackingInformationListField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        public TrackingInformation[] TrackingInformationList {
            get {
                return this.trackingInformationListField;
            }
            set {
                this.trackingInformationListField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3053")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://purolator.com/pws/datatypes/v1")]
    public partial class TrackPackagesByPinResponseContainer : ResponseContainer {
        
        private TrackingInformation[] trackingInformationListField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        public TrackingInformation[] TrackingInformationList {
            get {
                return this.trackingInformationListField;
            }
            set {
                this.trackingInformationListField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3053")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://purolator.com/pws/datatypes/v1")]
    public partial class TrackPackageByReferenceSearchCriteria {
        
        private string referenceField;
        
        private string destinationPostalCodeField;
        
        private string destinationCountryCodeField;
        
        private string billingAccountNumberField;
        
        private string shipmentFromDateField;
        
        private string shipmentToDateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Reference {
            get {
                return this.referenceField;
            }
            set {
                this.referenceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string DestinationPostalCode {
            get {
                return this.destinationPostalCodeField;
            }
            set {
                this.destinationPostalCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string DestinationCountryCode {
            get {
                return this.destinationCountryCodeField;
            }
            set {
                this.destinationCountryCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string BillingAccountNumber {
            get {
                return this.billingAccountNumberField;
            }
            set {
                this.billingAccountNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ShipmentFromDate {
            get {
                return this.shipmentFromDateField;
            }
            set {
                this.shipmentFromDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ShipmentToDate {
            get {
                return this.shipmentToDateField;
            }
            set {
                this.shipmentToDateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(GetDeliveryDetailsRequestContainer))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(TrackPackagesByReferenceRequestContainer))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(TrackPackagesByPinRequestContainer))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3053")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://purolator.com/pws/datatypes/v1")]
    public partial class RequestContainer {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3053")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://purolator.com/pws/datatypes/v1")]
    public partial class GetDeliveryDetailsRequestContainer : RequestContainer {
        
        private PIN pINField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public PIN PIN {
            get {
                return this.pINField;
            }
            set {
                this.pINField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3053")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://purolator.com/pws/datatypes/v1")]
    public partial class TrackPackagesByReferenceRequestContainer : RequestContainer {
        
        private TrackPackageByReferenceSearchCriteria trackPackageByReferenceSearchCriteriaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public TrackPackageByReferenceSearchCriteria TrackPackageByReferenceSearchCriteria {
            get {
                return this.trackPackageByReferenceSearchCriteriaField;
            }
            set {
                this.trackPackageByReferenceSearchCriteriaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3053")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://purolator.com/pws/datatypes/v1")]
    public partial class TrackPackagesByPinRequestContainer : RequestContainer {
        
        private PIN[] pINsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        public PIN[] PINs {
            get {
                return this.pINsField;
            }
            set {
                this.pINsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3053")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://purolator.com/pws/datatypes/v1")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://purolator.com/pws/datatypes/v1", IsNullable=true)]
    public partial class RequestContext : System.Web.Services.Protocols.SoapHeader {
        
        private string versionField;
        
        private Language languageField;
        
        private string groupIDField;
        
        private string requestReferenceField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
            }
        }
        
        /// <remarks/>
        public Language Language {
            get {
                return this.languageField;
            }
            set {
                this.languageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string GroupID {
            get {
                return this.groupIDField;
            }
            set {
                this.groupIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string RequestReference {
            get {
                return this.requestReferenceField;
            }
            set {
                this.requestReferenceField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3053")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://purolator.com/pws/datatypes/v1")]
    public enum Language {
        
        /// <remarks/>
        en,
        
        /// <remarks/>
        fr,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    public delegate void TrackPackagesByPinCompletedEventHandler(object sender, TrackPackagesByPinCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TrackPackagesByPinCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal TrackPackagesByPinCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public TrackPackagesByPinResponseContainer Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((TrackPackagesByPinResponseContainer)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    public delegate void TrackPackagesByReferenceCompletedEventHandler(object sender, TrackPackagesByReferenceCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TrackPackagesByReferenceCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal TrackPackagesByReferenceCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public TrackPackagesByReferenceResponseContainer Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((TrackPackagesByReferenceResponseContainer)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    public delegate void GetDeliveryDetailsCompletedEventHandler(object sender, GetDeliveryDetailsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.3053")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetDeliveryDetailsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetDeliveryDetailsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public GetDeliveryDetailsResponseContainer Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((GetDeliveryDetailsResponseContainer)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591