//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RetroMarket.PosteCanada.Properties
{


    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase
    {

        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));

        public static Settings Default
        {
            get
            {
                return defaultInstance;
            }
        }

        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://devwebservices.purolator.com/PWS/V1/ServiceAvailability/ServiceAvailabili" +
            "tyService.asmx")]
        public string PWSTestClient_ServiceAvailabilityProxy_ServiceAvailabilityService
        {
            get
            {
                return ((string)(this["PWSTestClient_ServiceAvailabilityProxy_ServiceAvailabilityService"]));
            }
        }

        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://devwebservices.purolator.com/EWS/V1/Estimating/EstimatingService.asmx")]
        public string PWSTestClient_EstimatingProxy_EstimatingService
        {
            get
            {
                return ((string)(this["PWSTestClient_EstimatingProxy_EstimatingService"]));
            }
        }
    }
}
