//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace RetroMarket.PosteCanada.EstimatingProxy
{
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1098.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name = "EstimatingServiceEndpoint", Namespace = "http://purolator.com/pws/service/v1")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ResponseContainer))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(RequestContainer))]
    public partial class EstimatingService : System.Web.Services.Protocols.SoapHttpClientProtocol
    {

        private RequestContext requestContextValueField;

        private ResponseContext responseContextValueField;

        private System.Threading.SendOrPostCallback GetQuickEstimateOperationCompleted;

        private System.Threading.SendOrPostCallback GetFullEstimateOperationCompleted;

        private bool useDefaultCredentialsSetExplicitly;

        /// <remarks/>
        public EstimatingService()
        {
            this.Url = global::RetroMarket.PosteCanada.Properties.Settings.Default.PWSTestClient_EstimatingProxy_EstimatingService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true))
            {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else
            {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }

        public RequestContext RequestContextValue
        {
            get
            {
                return this.requestContextValueField;
            }
            set
            {
                this.requestContextValueField = value;
            }
        }

        public ResponseContext ResponseContextValue
        {
            get
            {
                return this.responseContextValueField;
            }
            set
            {
                this.responseContextValueField = value;
            }
        }

        public new string Url
        {
            get
            {
                return base.Url;
            }
            set
            {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true)
                            && (this.useDefaultCredentialsSetExplicitly == false))
                            && (this.IsLocalFileSystemWebService(value) == false)))
                {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }

        public new bool UseDefaultCredentials
        {
            get
            {
                return base.UseDefaultCredentials;
            }
            set
            {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }

        /// <remarks/>
        public event GetQuickEstimateCompletedEventHandler GetQuickEstimateCompleted;

        /// <remarks/>
        public event GetFullEstimateCompletedEventHandler GetFullEstimateCompleted;

        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("RequestContextValue")]
        [System.Web.Services.Protocols.SoapHeaderAttribute("ResponseContextValue", Direction = System.Web.Services.Protocols.SoapHeaderDirection.Out)]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://purolator.com/pws/service/v1/GetQuickEstimate", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("GetQuickEstimateResponse", Namespace = "http://purolator.com/pws/datatypes/v1", IsNullable = true)]
        public GetQuickEstimateResponseContainer GetQuickEstimate([System.Xml.Serialization.XmlElementAttribute(Namespace = "http://purolator.com/pws/datatypes/v1", IsNullable = true)] GetQuickEstimateRequestContainer GetQuickEstimateRequest)
        {
            object[] results = this.Invoke("GetQuickEstimate", new object[] {
                        GetQuickEstimateRequest});
            return ((GetQuickEstimateResponseContainer)(results[0]));
        }

        /// <remarks/>
        public void GetQuickEstimateAsync(GetQuickEstimateRequestContainer GetQuickEstimateRequest)
        {
            this.GetQuickEstimateAsync(GetQuickEstimateRequest, null);
        }

        /// <remarks/>
        public void GetQuickEstimateAsync(GetQuickEstimateRequestContainer GetQuickEstimateRequest, object userState)
        {
            if ((this.GetQuickEstimateOperationCompleted == null))
            {
                this.GetQuickEstimateOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetQuickEstimateOperationCompleted);
            }
            this.InvokeAsync("GetQuickEstimate", new object[] {
                        GetQuickEstimateRequest}, this.GetQuickEstimateOperationCompleted, userState);
        }

        private void OnGetQuickEstimateOperationCompleted(object arg)
        {
            if ((this.GetQuickEstimateCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetQuickEstimateCompleted(this, new GetQuickEstimateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("RequestContextValue")]
        [System.Web.Services.Protocols.SoapHeaderAttribute("ResponseContextValue", Direction = System.Web.Services.Protocols.SoapHeaderDirection.Out)]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://purolator.com/pws/service/v1/GetFullEstimate", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("GetFullEstimateResponse", Namespace = "http://purolator.com/pws/datatypes/v1", IsNullable = true)]
        public GetFullEstimateResponseContainer GetFullEstimate([System.Xml.Serialization.XmlElementAttribute(Namespace = "http://purolator.com/pws/datatypes/v1", IsNullable = true)] GetFullEstimateRequestContainer GetFullEstimateRequest)
        {
            object[] results = this.Invoke("GetFullEstimate", new object[] {
                        GetFullEstimateRequest});
            return ((GetFullEstimateResponseContainer)(results[0]));
        }

        /// <remarks/>
        public void GetFullEstimateAsync(GetFullEstimateRequestContainer GetFullEstimateRequest)
        {
            this.GetFullEstimateAsync(GetFullEstimateRequest, null);
        }

        /// <remarks/>
        public void GetFullEstimateAsync(GetFullEstimateRequestContainer GetFullEstimateRequest, object userState)
        {
            if ((this.GetFullEstimateOperationCompleted == null))
            {
                this.GetFullEstimateOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetFullEstimateOperationCompleted);
            }
            this.InvokeAsync("GetFullEstimate", new object[] {
                        GetFullEstimateRequest}, this.GetFullEstimateOperationCompleted, userState);
        }

        private void OnGetFullEstimateOperationCompleted(object arg)
        {
            if ((this.GetFullEstimateCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetFullEstimateCompleted(this, new GetFullEstimateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        public new void CancelAsync(object userState)
        {
            base.CancelAsync(userState);
        }

        private bool IsLocalFileSystemWebService(string url)
        {
            if (((url == null)
                        || (url == string.Empty)))
            {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024)
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0)))
            {
                return true;
            }
            return false;
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1098.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://purolator.com/pws/datatypes/v1")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://purolator.com/pws/datatypes/v1", IsNullable = true)]
    public partial class RequestContext : System.Web.Services.Protocols.SoapHeader
    {

        private string versionField;

        private Language languageField;

        private string groupIDField;

        private string requestReferenceField;

        private string userTokenField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string Version
        {
            get
            {
                return this.versionField;
            }
            set
            {
                this.versionField = value;
            }
        }

        /// <remarks/>
        public Language Language
        {
            get
            {
                return this.languageField;
            }
            set
            {
                this.languageField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string GroupID
        {
            get
            {
                return this.groupIDField;
            }
            set
            {
                this.groupIDField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string RequestReference
        {
            get
            {
                return this.requestReferenceField;
            }
            set
            {
                this.requestReferenceField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string UserToken
        {
            get
            {
                return this.userTokenField;
            }
            set
            {
                this.userTokenField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1098.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://purolator.com/pws/datatypes/v1")]
    public enum Language
    {

        /// <remarks/>
        en,

        /// <remarks/>
        fr,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1098.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://purolator.com/pws/datatypes/v1")]
    public partial class OptionPrice
    {

        private decimal amountField;

        private string idField;

        private string descriptionField;

        /// <remarks/>
        public decimal Amount
        {
            get
            {
                return this.amountField;
            }
            set
            {
                this.amountField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string ID
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string Description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1098.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://purolator.com/pws/datatypes/v1")]
    public partial class Tax
    {

        private decimal amountField;

        private string typeField;

        private string descriptionField;

        /// <remarks/>
        public decimal Amount
        {
            get
            {
                return this.amountField;
            }
            set
            {
                this.amountField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string Type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string Description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1098.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://purolator.com/pws/datatypes/v1")]
    public partial class Surcharge
    {

        private decimal amountField;

        private string typeField;

        private string descriptionField;

        /// <remarks/>
        public decimal Amount
        {
            get
            {
                return this.amountField;
            }
            set
            {
                this.amountField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string Type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string Description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1098.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://purolator.com/pws/datatypes/v1")]
    public partial class ShipmentEstimate
    {

        private string serviceIDField;

        private string shipmentDateField;

        private string expectedDeliveryDateField;

        private int estimatedTransitDaysField;

        private bool estimatedTransitDaysFieldSpecified;

        private decimal basePriceField;

        private Surcharge[] surchargesField;

        private Tax[] taxesField;

        private OptionPrice[] optionPricesField;

        private decimal totalPriceField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string ServiceID
        {
            get
            {
                return this.serviceIDField;
            }
            set
            {
                this.serviceIDField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string ShipmentDate
        {
            get
            {
                return this.shipmentDateField;
            }
            set
            {
                this.shipmentDateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string ExpectedDeliveryDate
        {
            get
            {
                return this.expectedDeliveryDateField;
            }
            set
            {
                this.expectedDeliveryDateField = value;
            }
        }

        /// <remarks/>
        public int EstimatedTransitDays
        {
            get
            {
                return this.estimatedTransitDaysField;
            }
            set
            {
                this.estimatedTransitDaysField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool EstimatedTransitDaysSpecified
        {
            get
            {
                return this.estimatedTransitDaysFieldSpecified;
            }
            set
            {
                this.estimatedTransitDaysFieldSpecified = value;
            }
        }

        /// <remarks/>
        public decimal BasePrice
        {
            get
            {
                return this.basePriceField;
            }
            set
            {
                this.basePriceField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable = true)]
        public Surcharge[] Surcharges
        {
            get
            {
                return this.surchargesField;
            }
            set
            {
                this.surchargesField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable = true)]
        public Tax[] Taxes
        {
            get
            {
                return this.taxesField;
            }
            set
            {
                this.taxesField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable = true)]
        public OptionPrice[] OptionPrices
        {
            get
            {
                return this.optionPricesField;
            }
            set
            {
                this.optionPricesField = value;
            }
        }

        /// <remarks/>
        public decimal TotalPrice
        {
            get
            {
                return this.totalPriceField;
            }
            set
            {
                this.totalPriceField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1098.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://purolator.com/pws/datatypes/v1")]
    public partial class InformationalMessage
    {

        private string codeField;

        private string messageField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string Code
        {
            get
            {
                return this.codeField;
            }
            set
            {
                this.codeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string Message
        {
            get
            {
                return this.messageField;
            }
            set
            {
                this.messageField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1098.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://purolator.com/pws/datatypes/v1")]
    public partial class Error
    {

        private string codeField;

        private string descriptionField;

        private string additionalInformationField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string Code
        {
            get
            {
                return this.codeField;
            }
            set
            {
                this.codeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string Description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string AdditionalInformation
        {
            get
            {
                return this.additionalInformationField;
            }
            set
            {
                this.additionalInformationField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1098.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://purolator.com/pws/datatypes/v1")]
    public partial class ResponseInformation
    {

        private Error[] errorsField;

        private InformationalMessage[] informationalMessagesField;

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable = true)]
        public Error[] Errors
        {
            get
            {
                return this.errorsField;
            }
            set
            {
                this.errorsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable = true)]
        public InformationalMessage[] InformationalMessages
        {
            get
            {
                return this.informationalMessagesField;
            }
            set
            {
                this.informationalMessagesField = value;
            }
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(GetFullEstimateResponseContainer))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(GetQuickEstimateResponseContainer))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1098.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://purolator.com/pws/datatypes/v1")]
    public partial class ResponseContainer
    {

        private ResponseInformation responseInformationField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public ResponseInformation ResponseInformation
        {
            get
            {
                return this.responseInformationField;
            }
            set
            {
                this.responseInformationField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1098.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://purolator.com/pws/datatypes/v1")]
    public partial class GetFullEstimateResponseContainer : ResponseContainer
    {

        private ShipmentEstimate[] shipmentEstimatesField;

        private ShipmentEstimate[] returnShipmentEstimatesField;

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable = true)]
        public ShipmentEstimate[] ShipmentEstimates
        {
            get
            {
                return this.shipmentEstimatesField;
            }
            set
            {
                this.shipmentEstimatesField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable = true)]
        public ShipmentEstimate[] ReturnShipmentEstimates
        {
            get
            {
                return this.returnShipmentEstimatesField;
            }
            set
            {
                this.returnShipmentEstimatesField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1098.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://purolator.com/pws/datatypes/v1")]
    public partial class GetQuickEstimateResponseContainer : ResponseContainer
    {

        private ShipmentEstimate[] shipmentEstimatesField;

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable = true)]
        public ShipmentEstimate[] ShipmentEstimates
        {
            get
            {
                return this.shipmentEstimatesField;
            }
            set
            {
                this.shipmentEstimatesField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1098.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://purolator.com/pws/datatypes/v1")]
    public partial class OtherInformation
    {

        private string costCentreField;

        private string specialInstructionsField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string CostCentre
        {
            get
            {
                return this.costCentreField;
            }
            set
            {
                this.costCentreField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string SpecialInstructions
        {
            get
            {
                return this.specialInstructionsField;
            }
            set
            {
                this.specialInstructionsField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1098.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://purolator.com/pws/datatypes/v1")]
    public partial class TrackingReferenceInformation
    {

        private string reference1Field;

        private string reference2Field;

        private string reference3Field;

        private string reference4Field;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string Reference1
        {
            get
            {
                return this.reference1Field;
            }
            set
            {
                this.reference1Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string Reference2
        {
            get
            {
                return this.reference2Field;
            }
            set
            {
                this.reference2Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string Reference3
        {
            get
            {
                return this.reference3Field;
            }
            set
            {
                this.reference3Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string Reference4
        {
            get
            {
                return this.reference4Field;
            }
            set
            {
                this.reference4Field = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1098.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://purolator.com/pws/datatypes/v1")]
    public partial class NotificationInformation
    {

        private string confirmationEmailAddressField;

        private string advancedShippingNotificationEmailAddress1Field;

        private string advancedShippingNotificationEmailAddress2Field;

        private string advancedShippingNotificationMessageField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string ConfirmationEmailAddress
        {
            get
            {
                return this.confirmationEmailAddressField;
            }
            set
            {
                this.confirmationEmailAddressField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string AdvancedShippingNotificationEmailAddress1
        {
            get
            {
                return this.advancedShippingNotificationEmailAddress1Field;
            }
            set
            {
                this.advancedShippingNotificationEmailAddress1Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string AdvancedShippingNotificationEmailAddress2
        {
            get
            {
                return this.advancedShippingNotificationEmailAddress2Field;
            }
            set
            {
                this.advancedShippingNotificationEmailAddress2Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string AdvancedShippingNotificationMessage
        {
            get
            {
                return this.advancedShippingNotificationMessageField;
            }
            set
            {
                this.advancedShippingNotificationMessageField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1098.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://purolator.com/pws/datatypes/v1")]
    public partial class PickupInformation
    {

        private PickupType pickupTypeField;

        /// <remarks/>
        public PickupType PickupType
        {
            get
            {
                return this.pickupTypeField;
            }
            set
            {
                this.pickupTypeField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1098.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://purolator.com/pws/datatypes/v1")]
    public enum PickupType
    {

        /// <remarks/>
        DropOff,

        /// <remarks/>
        PreScheduled,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1098.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://purolator.com/pws/datatypes/v1")]
    public partial class CreditCardInformation
    {

        private CreditCardType typeField;

        private string numberField;

        private string nameField;

        private int expiryMonthField;

        private int expiryYearField;

        private string cVVField;

        /// <remarks/>
        public CreditCardType Type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string Number
        {
            get
            {
                return this.numberField;
            }
            set
            {
                this.numberField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        /// <remarks/>
        public int ExpiryMonth
        {
            get
            {
                return this.expiryMonthField;
            }
            set
            {
                this.expiryMonthField = value;
            }
        }

        /// <remarks/>
        public int ExpiryYear
        {
            get
            {
                return this.expiryYearField;
            }
            set
            {
                this.expiryYearField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string CVV
        {
            get
            {
                return this.cVVField;
            }
            set
            {
                this.cVVField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1098.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://purolator.com/pws/datatypes/v1")]
    public enum CreditCardType
    {

        /// <remarks/>
        Visa,

        /// <remarks/>
        MasterCard,

        /// <remarks/>
        AmericanExpress,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1098.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://purolator.com/pws/datatypes/v1")]
    public partial class PaymentInformation
    {

        private PaymentType paymentTypeField;

        private string registeredAccountNumberField;

        private string billingAccountNumberField;

        private CreditCardInformation creditCardInformationField;

        /// <remarks/>
        public PaymentType PaymentType
        {
            get
            {
                return this.paymentTypeField;
            }
            set
            {
                this.paymentTypeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string RegisteredAccountNumber
        {
            get
            {
                return this.registeredAccountNumberField;
            }
            set
            {
                this.registeredAccountNumberField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string BillingAccountNumber
        {
            get
            {
                return this.billingAccountNumberField;
            }
            set
            {
                this.billingAccountNumberField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public CreditCardInformation CreditCardInformation
        {
            get
            {
                return this.creditCardInformationField;
            }
            set
            {
                this.creditCardInformationField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1098.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://purolator.com/pws/datatypes/v1")]
    public enum PaymentType
    {

        /// <remarks/>
        Sender,

        /// <remarks/>
        Receiver,

        /// <remarks/>
        ThirdParty,

        /// <remarks/>
        CreditCard,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1098.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://purolator.com/pws/datatypes/v1")]
    public partial class ReturnShipment
    {

        private SenderInformation senderInformationField;

        private ReceiverInformation receiverInformationField;

        private PackageInformation packageInformationField;

        private PaymentInformation paymentInformationField;

        private PickupInformation pickupInformationField;

        private NotificationInformation notificationInformationField;

        private TrackingReferenceInformation trackingReferenceInformationField;

        private OtherInformation otherInformationField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public SenderInformation SenderInformation
        {
            get
            {
                return this.senderInformationField;
            }
            set
            {
                this.senderInformationField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public ReceiverInformation ReceiverInformation
        {
            get
            {
                return this.receiverInformationField;
            }
            set
            {
                this.receiverInformationField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public PackageInformation PackageInformation
        {
            get
            {
                return this.packageInformationField;
            }
            set
            {
                this.packageInformationField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public PaymentInformation PaymentInformation
        {
            get
            {
                return this.paymentInformationField;
            }
            set
            {
                this.paymentInformationField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public PickupInformation PickupInformation
        {
            get
            {
                return this.pickupInformationField;
            }
            set
            {
                this.pickupInformationField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public NotificationInformation NotificationInformation
        {
            get
            {
                return this.notificationInformationField;
            }
            set
            {
                this.notificationInformationField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public TrackingReferenceInformation TrackingReferenceInformation
        {
            get
            {
                return this.trackingReferenceInformationField;
            }
            set
            {
                this.trackingReferenceInformationField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public OtherInformation OtherInformation
        {
            get
            {
                return this.otherInformationField;
            }
            set
            {
                this.otherInformationField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1098.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://purolator.com/pws/datatypes/v1")]
    public partial class SenderInformation
    {

        private Address addressField;

        private string taxNumberField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public Address Address
        {
            get
            {
                return this.addressField;
            }
            set
            {
                this.addressField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string TaxNumber
        {
            get
            {
                return this.taxNumberField;
            }
            set
            {
                this.taxNumberField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1098.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://purolator.com/pws/datatypes/v1")]
    public partial class Address
    {

        private string nameField;

        private string companyField;

        private string departmentField;

        private string streetNumberField;

        private string streetSuffixField;

        private string streetNameField;

        private string streetTypeField;

        private string streetDirectionField;

        private string suiteField;

        private string floorField;

        private string streetAddress2Field;

        private string streetAddress3Field;

        private string cityField;

        private string provinceField;

        private string countryField;

        private string postalCodeField;

        private PhoneNumber phoneNumberField;

        private PhoneNumber faxNumberField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string Company
        {
            get
            {
                return this.companyField;
            }
            set
            {
                this.companyField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string Department
        {
            get
            {
                return this.departmentField;
            }
            set
            {
                this.departmentField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string StreetNumber
        {
            get
            {
                return this.streetNumberField;
            }
            set
            {
                this.streetNumberField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string StreetSuffix
        {
            get
            {
                return this.streetSuffixField;
            }
            set
            {
                this.streetSuffixField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string StreetName
        {
            get
            {
                return this.streetNameField;
            }
            set
            {
                this.streetNameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string StreetType
        {
            get
            {
                return this.streetTypeField;
            }
            set
            {
                this.streetTypeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string StreetDirection
        {
            get
            {
                return this.streetDirectionField;
            }
            set
            {
                this.streetDirectionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string Suite
        {
            get
            {
                return this.suiteField;
            }
            set
            {
                this.suiteField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string Floor
        {
            get
            {
                return this.floorField;
            }
            set
            {
                this.floorField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string StreetAddress2
        {
            get
            {
                return this.streetAddress2Field;
            }
            set
            {
                this.streetAddress2Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string StreetAddress3
        {
            get
            {
                return this.streetAddress3Field;
            }
            set
            {
                this.streetAddress3Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string City
        {
            get
            {
                return this.cityField;
            }
            set
            {
                this.cityField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string Province
        {
            get
            {
                return this.provinceField;
            }
            set
            {
                this.provinceField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string Country
        {
            get
            {
                return this.countryField;
            }
            set
            {
                this.countryField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string PostalCode
        {
            get
            {
                return this.postalCodeField;
            }
            set
            {
                this.postalCodeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public PhoneNumber PhoneNumber
        {
            get
            {
                return this.phoneNumberField;
            }
            set
            {
                this.phoneNumberField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public PhoneNumber FaxNumber
        {
            get
            {
                return this.faxNumberField;
            }
            set
            {
                this.faxNumberField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1098.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://purolator.com/pws/datatypes/v1")]
    public partial class PhoneNumber
    {

        private string countryCodeField;

        private string areaCodeField;

        private string phoneField;

        private string extensionField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string CountryCode
        {
            get
            {
                return this.countryCodeField;
            }
            set
            {
                this.countryCodeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string AreaCode
        {
            get
            {
                return this.areaCodeField;
            }
            set
            {
                this.areaCodeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string Phone
        {
            get
            {
                return this.phoneField;
            }
            set
            {
                this.phoneField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string Extension
        {
            get
            {
                return this.extensionField;
            }
            set
            {
                this.extensionField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1098.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://purolator.com/pws/datatypes/v1")]
    public partial class ReceiverInformation
    {

        private Address addressField;

        private string taxNumberField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public Address Address
        {
            get
            {
                return this.addressField;
            }
            set
            {
                this.addressField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string TaxNumber
        {
            get
            {
                return this.taxNumberField;
            }
            set
            {
                this.taxNumberField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1098.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://purolator.com/pws/datatypes/v1")]
    public partial class PackageInformation
    {

        private string serviceIDField;

        private string descriptionField;

        private TotalWeight totalWeightField;

        private int totalPiecesField;

        private Piece[] piecesInformationField;

        private bool dangerousGoodsDeclarationDocumentIndicatorField;

        private bool dangerousGoodsDeclarationDocumentIndicatorFieldSpecified;

        private OptionsInformation optionsInformationField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string ServiceID
        {
            get
            {
                return this.serviceIDField;
            }
            set
            {
                this.serviceIDField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string Description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public TotalWeight TotalWeight
        {
            get
            {
                return this.totalWeightField;
            }
            set
            {
                this.totalWeightField = value;
            }
        }

        /// <remarks/>
        public int TotalPieces
        {
            get
            {
                return this.totalPiecesField;
            }
            set
            {
                this.totalPiecesField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable = true)]
        public Piece[] PiecesInformation
        {
            get
            {
                return this.piecesInformationField;
            }
            set
            {
                this.piecesInformationField = value;
            }
        }

        /// <remarks/>
        public bool DangerousGoodsDeclarationDocumentIndicator
        {
            get
            {
                return this.dangerousGoodsDeclarationDocumentIndicatorField;
            }
            set
            {
                this.dangerousGoodsDeclarationDocumentIndicatorField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DangerousGoodsDeclarationDocumentIndicatorSpecified
        {
            get
            {
                return this.dangerousGoodsDeclarationDocumentIndicatorFieldSpecified;
            }
            set
            {
                this.dangerousGoodsDeclarationDocumentIndicatorFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public OptionsInformation OptionsInformation
        {
            get
            {
                return this.optionsInformationField;
            }
            set
            {
                this.optionsInformationField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1098.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://purolator.com/pws/datatypes/v1")]
    public partial class TotalWeight
    {

        private System.Nullable<int> valueField;

        private WeightUnit weightUnitField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public System.Nullable<int> Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }

        /// <remarks/>
        public WeightUnit WeightUnit
        {
            get
            {
                return this.weightUnitField;
            }
            set
            {
                this.weightUnitField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1098.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://purolator.com/pws/datatypes/v1")]
    public enum WeightUnit
    {

        /// <remarks/>
        lb,

        /// <remarks/>
        kg,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1098.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://purolator.com/pws/datatypes/v1")]
    public partial class Piece
    {

        private Weight weightField;

        private Dimension lengthField;

        private Dimension widthField;

        private Dimension heightField;

        private OptionIDValuePair[] optionsField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public Weight Weight
        {
            get
            {
                return this.weightField;
            }
            set
            {
                this.weightField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public Dimension Length
        {
            get
            {
                return this.lengthField;
            }
            set
            {
                this.lengthField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public Dimension Width
        {
            get
            {
                return this.widthField;
            }
            set
            {
                this.widthField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public Dimension Height
        {
            get
            {
                return this.heightField;
            }
            set
            {
                this.heightField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable = true)]
        public OptionIDValuePair[] Options
        {
            get
            {
                return this.optionsField;
            }
            set
            {
                this.optionsField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1098.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://purolator.com/pws/datatypes/v1")]
    public partial class Weight
    {

        private System.Nullable<decimal> valueField;

        private WeightUnit weightUnitField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public System.Nullable<decimal> Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }

        /// <remarks/>
        public WeightUnit WeightUnit
        {
            get
            {
                return this.weightUnitField;
            }
            set
            {
                this.weightUnitField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1098.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://purolator.com/pws/datatypes/v1")]
    public partial class Dimension
    {

        private System.Nullable<decimal> valueField;

        private DimensionUnit dimensionUnitField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public System.Nullable<decimal> Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }

        /// <remarks/>
        public DimensionUnit DimensionUnit
        {
            get
            {
                return this.dimensionUnitField;
            }
            set
            {
                this.dimensionUnitField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1098.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://purolator.com/pws/datatypes/v1")]
    public enum DimensionUnit
    {

        /// <remarks/>
        @in,

        /// <remarks/>
        cm,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1098.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://purolator.com/pws/datatypes/v1")]
    public partial class OptionIDValuePair
    {

        private string idField;

        private string valueField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string ID
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1098.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://purolator.com/pws/datatypes/v1")]
    public partial class OptionsInformation
    {

        private OptionIDValuePair[] optionsField;

        private Address expressChequeAddressField;

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable = true)]
        public OptionIDValuePair[] Options
        {
            get
            {
                return this.optionsField;
            }
            set
            {
                this.optionsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public Address ExpressChequeAddress
        {
            get
            {
                return this.expressChequeAddressField;
            }
            set
            {
                this.expressChequeAddressField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1098.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://purolator.com/pws/datatypes/v1")]
    public partial class ReturnShipmentInformation
    {

        private int numberOfReturnShipmentsField;

        private ReturnShipment returnShipmentField;

        /// <remarks/>
        public int NumberOfReturnShipments
        {
            get
            {
                return this.numberOfReturnShipmentsField;
            }
            set
            {
                this.numberOfReturnShipmentsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public ReturnShipment ReturnShipment
        {
            get
            {
                return this.returnShipmentField;
            }
            set
            {
                this.returnShipmentField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1098.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://purolator.com/pws/datatypes/v1")]
    public partial class DutyInformation
    {

        private System.Nullable<BillDutiesToParty> billDutiesToPartyField;

        private System.Nullable<BusinessRelationship> businessRelationshipField;

        private System.Nullable<DutyCurrency> currencyField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public System.Nullable<BillDutiesToParty> BillDutiesToParty
        {
            get
            {
                return this.billDutiesToPartyField;
            }
            set
            {
                this.billDutiesToPartyField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public System.Nullable<BusinessRelationship> BusinessRelationship
        {
            get
            {
                return this.businessRelationshipField;
            }
            set
            {
                this.businessRelationshipField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public System.Nullable<DutyCurrency> Currency
        {
            get
            {
                return this.currencyField;
            }
            set
            {
                this.currencyField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1098.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://purolator.com/pws/datatypes/v1")]
    public enum BillDutiesToParty
    {

        /// <remarks/>
        Sender,

        /// <remarks/>
        Receiver,

        /// <remarks/>
        Buyer,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1098.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://purolator.com/pws/datatypes/v1")]
    public enum BusinessRelationship
    {

        /// <remarks/>
        Related,

        /// <remarks/>
        NotRelated,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1098.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://purolator.com/pws/datatypes/v1")]
    public enum DutyCurrency
    {

        /// <remarks/>
        CAD,

        /// <remarks/>
        USD,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1098.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://purolator.com/pws/datatypes/v1")]
    public partial class BuyerInformation
    {

        private Address addressField;

        private string taxNumberField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public Address Address
        {
            get
            {
                return this.addressField;
            }
            set
            {
                this.addressField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string TaxNumber
        {
            get
            {
                return this.taxNumberField;
            }
            set
            {
                this.taxNumberField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1098.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://purolator.com/pws/datatypes/v1")]
    public partial class ContentDetail
    {

        private string descriptionField;

        private string harmonizedCodeField;

        private string countryOfManufactureField;

        private string productCodeField;

        private decimal unitValueField;

        private int quantityField;

        private bool nAFTADocumentIndicatorField;

        private bool nAFTADocumentIndicatorFieldSpecified;

        private bool fDADocumentIndicatorField;

        private bool fDADocumentIndicatorFieldSpecified;

        private bool fCCDocumentIndicatorField;

        private bool fCCDocumentIndicatorFieldSpecified;

        private bool senderIsProducerIndicatorField;

        private bool senderIsProducerIndicatorFieldSpecified;

        private bool textileIndicatorField;

        private bool textileIndicatorFieldSpecified;

        private string textileManufacturerField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string Description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string HarmonizedCode
        {
            get
            {
                return this.harmonizedCodeField;
            }
            set
            {
                this.harmonizedCodeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string CountryOfManufacture
        {
            get
            {
                return this.countryOfManufactureField;
            }
            set
            {
                this.countryOfManufactureField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string ProductCode
        {
            get
            {
                return this.productCodeField;
            }
            set
            {
                this.productCodeField = value;
            }
        }

        /// <remarks/>
        public decimal UnitValue
        {
            get
            {
                return this.unitValueField;
            }
            set
            {
                this.unitValueField = value;
            }
        }

        /// <remarks/>
        public int Quantity
        {
            get
            {
                return this.quantityField;
            }
            set
            {
                this.quantityField = value;
            }
        }

        /// <remarks/>
        public bool NAFTADocumentIndicator
        {
            get
            {
                return this.nAFTADocumentIndicatorField;
            }
            set
            {
                this.nAFTADocumentIndicatorField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool NAFTADocumentIndicatorSpecified
        {
            get
            {
                return this.nAFTADocumentIndicatorFieldSpecified;
            }
            set
            {
                this.nAFTADocumentIndicatorFieldSpecified = value;
            }
        }

        /// <remarks/>
        public bool FDADocumentIndicator
        {
            get
            {
                return this.fDADocumentIndicatorField;
            }
            set
            {
                this.fDADocumentIndicatorField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool FDADocumentIndicatorSpecified
        {
            get
            {
                return this.fDADocumentIndicatorFieldSpecified;
            }
            set
            {
                this.fDADocumentIndicatorFieldSpecified = value;
            }
        }

        /// <remarks/>
        public bool FCCDocumentIndicator
        {
            get
            {
                return this.fCCDocumentIndicatorField;
            }
            set
            {
                this.fCCDocumentIndicatorField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool FCCDocumentIndicatorSpecified
        {
            get
            {
                return this.fCCDocumentIndicatorFieldSpecified;
            }
            set
            {
                this.fCCDocumentIndicatorFieldSpecified = value;
            }
        }

        /// <remarks/>
        public bool SenderIsProducerIndicator
        {
            get
            {
                return this.senderIsProducerIndicatorField;
            }
            set
            {
                this.senderIsProducerIndicatorField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SenderIsProducerIndicatorSpecified
        {
            get
            {
                return this.senderIsProducerIndicatorFieldSpecified;
            }
            set
            {
                this.senderIsProducerIndicatorFieldSpecified = value;
            }
        }

        /// <remarks/>
        public bool TextileIndicator
        {
            get
            {
                return this.textileIndicatorField;
            }
            set
            {
                this.textileIndicatorField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TextileIndicatorSpecified
        {
            get
            {
                return this.textileIndicatorFieldSpecified;
            }
            set
            {
                this.textileIndicatorFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string TextileManufacturer
        {
            get
            {
                return this.textileManufacturerField;
            }
            set
            {
                this.textileManufacturerField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1098.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://purolator.com/pws/datatypes/v1")]
    public partial class InternationalInformation
    {

        private bool documentsOnlyIndicatorField;

        private ContentDetail[] contentDetailsField;

        private BuyerInformation buyerInformationField;

        private string preferredCustomsBrokerField;

        private DutyInformation dutyInformationField;

        private System.Nullable<ImportExportType> importExportTypeField;

        private bool importExportTypeFieldSpecified;

        private bool customsInvoiceDocumentIndicatorField;

        private bool customsInvoiceDocumentIndicatorFieldSpecified;

        /// <remarks/>
        public bool DocumentsOnlyIndicator
        {
            get
            {
                return this.documentsOnlyIndicatorField;
            }
            set
            {
                this.documentsOnlyIndicatorField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable = true)]
        public ContentDetail[] ContentDetails
        {
            get
            {
                return this.contentDetailsField;
            }
            set
            {
                this.contentDetailsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public BuyerInformation BuyerInformation
        {
            get
            {
                return this.buyerInformationField;
            }
            set
            {
                this.buyerInformationField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string PreferredCustomsBroker
        {
            get
            {
                return this.preferredCustomsBrokerField;
            }
            set
            {
                this.preferredCustomsBrokerField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public DutyInformation DutyInformation
        {
            get
            {
                return this.dutyInformationField;
            }
            set
            {
                this.dutyInformationField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public System.Nullable<ImportExportType> ImportExportType
        {
            get
            {
                return this.importExportTypeField;
            }
            set
            {
                this.importExportTypeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ImportExportTypeSpecified
        {
            get
            {
                return this.importExportTypeFieldSpecified;
            }
            set
            {
                this.importExportTypeFieldSpecified = value;
            }
        }

        /// <remarks/>
        public bool CustomsInvoiceDocumentIndicator
        {
            get
            {
                return this.customsInvoiceDocumentIndicatorField;
            }
            set
            {
                this.customsInvoiceDocumentIndicatorField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CustomsInvoiceDocumentIndicatorSpecified
        {
            get
            {
                return this.customsInvoiceDocumentIndicatorFieldSpecified;
            }
            set
            {
                this.customsInvoiceDocumentIndicatorFieldSpecified = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1098.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://purolator.com/pws/datatypes/v1")]
    public enum ImportExportType
    {

        /// <remarks/>
        Permanent,

        /// <remarks/>
        Temporary,

        /// <remarks/>
        Repair,

        /// <remarks/>
        Return,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1098.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://purolator.com/pws/datatypes/v1")]
    public partial class Shipment
    {

        private SenderInformation senderInformationField;

        private ReceiverInformation receiverInformationField;

        private string shipmentDateField;

        private PackageInformation packageInformationField;

        private InternationalInformation internationalInformationField;

        private ReturnShipmentInformation returnShipmentInformationField;

        private PaymentInformation paymentInformationField;

        private PickupInformation pickupInformationField;

        private NotificationInformation notificationInformationField;

        private TrackingReferenceInformation trackingReferenceInformationField;

        private OtherInformation otherInformationField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public SenderInformation SenderInformation
        {
            get
            {
                return this.senderInformationField;
            }
            set
            {
                this.senderInformationField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public ReceiverInformation ReceiverInformation
        {
            get
            {
                return this.receiverInformationField;
            }
            set
            {
                this.receiverInformationField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string ShipmentDate
        {
            get
            {
                return this.shipmentDateField;
            }
            set
            {
                this.shipmentDateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public PackageInformation PackageInformation
        {
            get
            {
                return this.packageInformationField;
            }
            set
            {
                this.packageInformationField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public InternationalInformation InternationalInformation
        {
            get
            {
                return this.internationalInformationField;
            }
            set
            {
                this.internationalInformationField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public ReturnShipmentInformation ReturnShipmentInformation
        {
            get
            {
                return this.returnShipmentInformationField;
            }
            set
            {
                this.returnShipmentInformationField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public PaymentInformation PaymentInformation
        {
            get
            {
                return this.paymentInformationField;
            }
            set
            {
                this.paymentInformationField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public PickupInformation PickupInformation
        {
            get
            {
                return this.pickupInformationField;
            }
            set
            {
                this.pickupInformationField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public NotificationInformation NotificationInformation
        {
            get
            {
                return this.notificationInformationField;
            }
            set
            {
                this.notificationInformationField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public TrackingReferenceInformation TrackingReferenceInformation
        {
            get
            {
                return this.trackingReferenceInformationField;
            }
            set
            {
                this.trackingReferenceInformationField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public OtherInformation OtherInformation
        {
            get
            {
                return this.otherInformationField;
            }
            set
            {
                this.otherInformationField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1098.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://purolator.com/pws/datatypes/v1")]
    public partial class ShortAddress
    {

        private string cityField;

        private string provinceField;

        private string countryField;

        private string postalCodeField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string City
        {
            get
            {
                return this.cityField;
            }
            set
            {
                this.cityField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string Province
        {
            get
            {
                return this.provinceField;
            }
            set
            {
                this.provinceField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string Country
        {
            get
            {
                return this.countryField;
            }
            set
            {
                this.countryField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string PostalCode
        {
            get
            {
                return this.postalCodeField;
            }
            set
            {
                this.postalCodeField = value;
            }
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(GetFullEstimateRequestContainer))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(GetQuickEstimateRequestContainer))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1098.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://purolator.com/pws/datatypes/v1")]
    public partial class RequestContainer
    {
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1098.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://purolator.com/pws/datatypes/v1")]
    public partial class GetFullEstimateRequestContainer : RequestContainer
    {

        private Shipment shipmentField;

        private bool showAlternativeServicesIndicatorField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public Shipment Shipment
        {
            get
            {
                return this.shipmentField;
            }
            set
            {
                this.shipmentField = value;
            }
        }

        /// <remarks/>
        public bool ShowAlternativeServicesIndicator
        {
            get
            {
                return this.showAlternativeServicesIndicatorField;
            }
            set
            {
                this.showAlternativeServicesIndicatorField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1098.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://purolator.com/pws/datatypes/v1")]
    public partial class GetQuickEstimateRequestContainer : RequestContainer
    {

        private string billingAccountNumberField;

        private string senderPostalCodeField;

        private ShortAddress receiverAddressField;

        private string packageTypeField;

        private TotalWeight totalWeightField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string BillingAccountNumber
        {
            get
            {
                return this.billingAccountNumberField;
            }
            set
            {
                this.billingAccountNumberField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string SenderPostalCode
        {
            get
            {
                return this.senderPostalCodeField;
            }
            set
            {
                this.senderPostalCodeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public ShortAddress ReceiverAddress
        {
            get
            {
                return this.receiverAddressField;
            }
            set
            {
                this.receiverAddressField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string PackageType
        {
            get
            {
                return this.packageTypeField;
            }
            set
            {
                this.packageTypeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public TotalWeight TotalWeight
        {
            get
            {
                return this.totalWeightField;
            }
            set
            {
                this.totalWeightField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1098.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://purolator.com/pws/datatypes/v1")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://purolator.com/pws/datatypes/v1", IsNullable = true)]
    public partial class ResponseContext : System.Web.Services.Protocols.SoapHeader
    {

        private string responseReferenceField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string ResponseReference
        {
            get
            {
                return this.responseReferenceField;
            }
            set
            {
                this.responseReferenceField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1098.0")]
    public delegate void GetQuickEstimateCompletedEventHandler(object sender, GetQuickEstimateCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1098.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetQuickEstimateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal GetQuickEstimateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
                base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public GetQuickEstimateResponseContainer Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((GetQuickEstimateResponseContainer)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1098.0")]
    public delegate void GetFullEstimateCompletedEventHandler(object sender, GetFullEstimateCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1098.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetFullEstimateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal GetFullEstimateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
                base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public GetFullEstimateResponseContainer Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((GetFullEstimateResponseContainer)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591